Script started on 2020-09-25 19:17:19-06:00
]0;rupertraphael.amodia@csx3:~/cpsc-355/assign1[rupertraphael.amodia@csx3 assign1]$ as[K[K./assign1 5 6 occurrences.txt 
5  2  9  3  4  9  
6  8  1  2  8  0  
5  5  3  1  6  3  
5  8  6  9  5  9  
3  6  7  4  2  4  
Enter the index of the word you are searching for: 0
How many top documents you want to retrieve? 5
Top Documents with occurrences for 0:
 1. Doc 1 	 6 occurences 	 0.240000 frequency
 2. Doc 2 	 5 occurences 	 0.217391 frequency
 3. Doc 0 	 5 occurences 	 0.156250 frequency
 4. Doc 3 	 5 occurences 	 0.119048 frequency
 5. Doc 4 	 3 occurences 	 0.115385 frequency
Do you want to continue? Enter n for no. Otherwise, enter any character to continue. y
Enter the index of the word you are searching for: 4
How many top documents you want to retrieve? 7
You're retrieving more documents than there are documents.
Retrieving 5 doc(s).Top Documents with occurrences for 4:
 1. Doc 1 	 8 occurences 	 0.320000 frequency
 2. Doc 2 	 6 occurences 	 0.260870 frequency
 3. Doc 0 	 4 occurences 	 0.125000 frequency
 4. Doc 3 	 5 occurences 	 0.119048 frequency
 5. Doc 4 	 2 occurences 	 0.076923 frequency
Do you want to continue? Enter n for no. Otherwise, enter any character to continue. y
Enter the index of the word you are searching for: 6
We're sorry but that word does not exist.
Please try again.
Enter the index of the word you are searching for: 5
How many top documents you want to retrieve? 2
Top Documents with occurrences for 5:
 1. Doc 0 	 9 occurences 	 0.281250 frequency
 2. Doc 3 	 9 occurences 	 0.214286 frequency
Do you want to continue? Enter n for no. Otherwise, enter any character to continue. n
]0;rupertraphael.amodia@csx3:~/cpsc-355/assign1[rupertraphael.amodia@csx3 assign1]$ ./assign1 10 10
8  6  2  6  8  6  9  8  7  1  
2  6  4  3  7  4  6  3  3  3  
4  5  3  4  4  6  9  3  4  6  
5  4  2  9  1  1  6  0  9  5  
1  1  3  5  4  0  0  2  4  3  
8  8  0  1  5  4  7  4  0  4  
1  5  8  5  6  9  6  4  2  5  
0  3  9  3  1  5  6  3  8  0  
8  6  0  8  9  5  5  6  2  5  
2  5  2  1  0  8  2  9  3  4  
Enter the index of the word you are searching for: 9
How many top documents you want to retrieve? 10
Top Documents with occurrences for 9:
 1. Doc 4 	 3 occurences 	 0.130435 frequency
 2. Doc 2 	 6 occurences 	 0.125000 frequency
 3. Doc 3 	 5 occurences 	 0.119048 frequency
 4. Doc 9 	 4 occurences 	 0.111111 frequency
 5. Doc 6 	 5 occurences 	 0.098039 frequency
 6. Doc 5 	 4 occurences 	 0.097561 frequency
 7. Doc 8 	 5 occurences 	 0.092593 frequency
 8. Doc 1 	 3 occurences 	 0.073171 frequency
 9. Doc 0 	 1 occurences 	 0.016393 frequency
10. Doc 7 	 0 occurences 	 0.000000 frequency
Do you want to continue? Enter n for no. Otherwise, enter any character to continue. 2
Enter the index of the word you are searching for: 1
How many top documents you want to retrieve? 1
Top Documents with occurrences for 1:
 1. Doc 5 	 8 occurences 	 0.195122 frequency
Do you want to continue? Enter n for no. Otherwise, enter any character to continue. y
Enter the index of the word you are searching for: 0
How many top documents you want to retrieve? 0
Top Documents with occurrences for 0:
Do you want to continue? Enter n for no. Otherwise, enter any character to continue. n y
Enter the index of the word you are searching for: 4
How many top documents you want to retrieve? 5
Top Documents with occurrences for 4:
 1. Doc 4 	 4 occurences 	 0.173913 frequency
 2. Doc 1 	 7 occurences 	 0.170732 frequency
 3. Doc 8 	 9 occurences 	 0.166667 frequency
 4. Doc 0 	 8 occurences 	 0.131148 frequency
 5. Doc 5 	 5 occurences 	 0.121951 frequency
Do you want to continue? Enter n for no. Otherwise, enter any character to continue. n
]0;rupertraphael.amodia@csx3:~/cpsc-355/assign1[rupertraphael.amodia@csx3 assign1]$ exit
exit

Script done on 2020-09-25 19:20:06-06:00
