Script started on 2020-10-26 22:33:30-06:00
]0;rupertraphael.amodia@csa2:~/cpsc-355/assign3[rupertraphael.amodia@csa2 assign3]$ exitgit pushcommit -m 'Add script file.'[10Padd script.script [12Pstatus./assign3 [6Pexit./assign3 

-15 x 10 = -150

-14 x 6 = -84

-13 x 2 = -26

-12 x 11 = -132

-11 x 2 = -22

-10 x 12 = -120

-9 x 12 = -108

-8 x 2 = -16

-7 x 12 = -84

-6 x 5 = -30

-5 x 7 = -35

-4 x 1 = -4

-3 x 2 = -6

-2 x 4 = -8

-1 x 6 = -6

0 x 13 = 0

1 x 3 = 3

2 x 13 = 26

3 x 1 = 3

4 x 7 = 28

5 x 12 = 60

6 x 4 = 24

7 x 13 = 91

8 x 7 = 56

9 x 0 = 0

10 x 5 = 50

11 x 8 = 88

12 x 2 = 24

13 x 11 = 143

14 x 1 = 14

15 x 4 = 60
]0;rupertraphael.amodia@csa2:~/cpsc-355/assign3[rupertraphael.amodia@csa2 assign3]$ exit
exit

Script done on 2020-10-26 22:33:35-06:00
